# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('inspect_date', models.DateField()),
                ('deadline', models.DateField()),
                ('report_date', models.DateField()),
                ('send_date', models.DateField()),
                ('is_scientific', models.CharField(choices=[('YES', '是'), ('NO', '否')], default='否', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='输入流水号', max_length=20)),
                ('sale_price', models.FloatField(default=0)),
                ('is_charge', models.CharField(choices=[('YES', '是'), ('NO', '否')], max_length=5)),
                ('invoice_id', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_company', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.FloatField(default=0)),
                ('receipt_id', models.CharField(blank=True, max_length=30, null=True)),
                ('receivable_way', models.CharField(default='输入回款方式', max_length=10)),
                ('bank_charges', models.FloatField(blank=True, null=True)),
                ('trade_receviable', models.FloatField(default=0)),
                ('actual_payment', models.FloatField(default=0)),
                ('settlement_price', models.FloatField(default=0)),
                ('cash_date', models.DateField()),
                ('cash_month', models.DateField()),
                ('voucher_id', models.CharField(default='输入用友凭证号', max_length=20)),
                ('promotion_expenses', models.FloatField(default=0)),
                ('promotion_date', models.DateField()),
                ('u8_month', models.DateField()),
                ('is_receipt', models.CharField(choices=[('YES', '是'), ('NO', '否')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('cancer', '实体肿瘤'), ('blood', '血液肿瘤')], max_length=30)),
                ('detect_content', models.CharField(choices=[('肺癌LONGLUNG', '肺癌LONGLUNG'), ('全外显子检测', '全外显子检测'), ('肺癌230基因', '肺癌230基因'), ('肺癌10基因', '肺癌10基因'), ('结直肠癌9基因', '结直肠癌9基因'), ('全癌种230基因', '全癌种230基因'), ('乳腺癌/卵巢癌BRCA1/2基因', '乳腺癌/卵巢癌BRCA1/2基因'), ('乳腺癌21基因', '乳腺癌21基因'), ('血液病基因检测', '血液病基因检测'), ('急性髓细胞白血病(AML)76基因检测', '急性髓细胞白血病(AML)76基因检测'), ('血液病化疗药物临床获益基因检测', '血液病化疗药物临床获益基因检测'), ('骨髓增生异常综合症(MDS)60基因检测', '骨髓增生异常综合症(MDS)60基因检测'), ('急性淋巴细胞白血病(ALL)基因检测', '急性淋巴细胞白血病(ALL)基因检测'), ('骨髓增殖性肿瘤(MPN)基因检测', '骨髓增殖性肿瘤(MPN)基因检测')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(default='HB00001', max_length=20)),
                ('sample_nation', models.CharField(blank=True, max_length=20, null=True)),
                ('sample_age', models.CharField(blank=True, max_length=20, null=True)),
                ('certificate_type', models.CharField(blank=True, max_length=10, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=18, null=True)),
                ('sample_name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=18, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=100, null=True)),
                ('submit_physician', models.CharField(blank=True, max_length=20, null=True)),
                ('physician_phone', models.CharField(blank=True, max_length=18, null=True)),
                ('medical_record_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citys', models.CharField(default='输入城市', max_length=10)),
                ('areas', models.CharField(default='输入地区', max_length=10)),
                ('market_represent', models.CharField(default='输入销售代表', max_length=10)),
                ('submit_hosptial', models.CharField(default='输入送检医院', max_length=20)),
                ('departments', models.CharField(default='输入科室', max_length=10)),
                ('station', models.CharField(default='输入岗位', max_length=10)),
                ('in_charge', models.CharField(default='输入负责人', max_length=10)),
                ('DSM', models.CharField(default='输入直属领导', max_length=10)),
                ('sale_price', models.FloatField(default=0)),
                ('agency_direct', models.CharField(choices=[('1', '代理'), ('2', '直营')], max_length=2)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acorndxData.PersonInfo')),
            ],
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='acorndxData.PersonInfo'),
        ),
        migrations.AddField(
            model_name='detectinfo',
            name='detect_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acorndxData.ItemsInfo'),
        ),
        migrations.AddField(
            model_name='detectinfo',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='acorndxData.PersonInfo'),
        ),
    ]
