# Generated by Django 2.0 on 2018-01-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodClinicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BloodResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CancerClinicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CancerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsId', models.IntegerField()),
                ('itemsChinese', models.CharField(default='中文列名', max_length=10)),
                ('itemsEnglish', models.CharField(default='English', max_length=20)),
                ('itemsType', models.CharField(default='char', max_length=5)),
                ('itemsLength', models.IntegerField(default=20)),
                ('isNull', models.CharField(blank=True, max_length=2, null=True)),
                ('isBlank', models.CharField(blank=True, max_length=2, null=True)),
                ('belongTable', models.CharField(max_length=20)),
                ('readRight', models.CharField(default='0', max_length=5)),
                ('writeRight', models.CharField(default='0', max_length=5)),
                ('illegality', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentId', models.IntegerField()),
                ('departmentName', models.CharField(default='departmentName', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='username', max_length=10)),
                ('userAccount', models.CharField(default='userAccount', max_length=20)),
                ('userPassword', models.CharField(default='userPassword', max_length=20)),
                ('userDepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acorndxData.Department')),
            ],
        ),
    ]
