# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0002_auto_20171128_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='trade_receivable',
            new_name='trade_receviable',
        ),
    ]
