# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0003_auto_20171213_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='receivable_way',
            field=models.CharField(default='输入回款方式', max_length=10),
        ),
    ]
