# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0004_auto_20171128_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinfo',
            name='detect_content',
            field=models.CharField(choices=[('1', '肺癌LONGLUNG'), ('2', '全外显子检测'), ('3', '肺癌230基因'), ('4', '肺癌10基因'), ('5', '结直肠癌9基因'), ('6', '全癌种230基因'), ('7', '乳腺癌/卵巢癌BRCA1/2基因'), ('8', '乳腺癌21基因'), ('9', '血液病基因检测'), ('10', '急性髓细胞白血病(AML)76基因检测'), ('11', '血液病化疗药物临床获益基因检测'), ('12', '骨髓增生异常综合症(MDS)60基因检测'), ('13', '急性淋巴细胞白血病(ALL)基因检测'), ('14', '骨髓增殖性肿瘤(MPN)基因检测')], max_length=2),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='project_type',
            field=models.CharField(choices=[('cancer', '实体肿瘤'), ('blood', '血液肿瘤')], max_length=10),
        ),
    ]
