# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0005_auto_20171130_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinfo',
            old_name='citys',
            new_name='cities',
        ),
        migrations.RenameField(
            model_name='saleinfo',
            old_name='submit_hosptial',
            new_name='submit_hospital',
        ),
    ]
