# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0005_auto_20171214_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinfo',
            name='sale_price',
        ),
    ]
