# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0006_remove_saleinfo_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectInfo',
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='detect_content',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='inspect_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='is_scientific',
            field=models.CharField(choices=[('YES', '是'), ('NO', '否')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
