# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acorndxData', '0006_auto_20171201_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='SP',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='itemsinfo',
            name='detect_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsinfo',
            name='detect_items',
            field=models.CharField(default='所属检测套餐', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='detect_content',
            field=models.CharField(default='检测内容', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemsinfo',
            name='project_type',
            field=models.CharField(default='实体瘤/血液病', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleinfo',
            name='agency_direct',
            field=models.CharField(default='直营', max_length=5),
        ),
    ]
